#!/bin/bash

# Installs zj-50 driver
# Tested as working under Ubuntu 16.04

/etc/init.d/cups stop
cp rastertozj80 /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/xprinter
cp ZJ-80-Fixed.ppd /usr/share/cups/model/xprinter/
cd /usr/lib/cups/filter
chmod 755 rastertozj80
chown root:root rastertozj80
cd -
/etc/init.d/cups start
